import { z } from 'zod';

/**
 * Aila Intelligence input (AILA-V1-SCOPE §7, PRODUCT-SPEC §10, §18). The
 * same schemas are used by the API and the browser so limits match.
 */

/** Capabilities a person may choose in Intelligence (PRODUCT-SPEC §10.2 "model selection where permitted"). */
export const INTELLIGENCE_CAPABILITIES = ['fast', 'balanced', 'reasoning'] as const;
export type IntelligenceCapability = (typeof INTELLIGENCE_CAPABILITIES)[number];

/**
 * Web search setting in the message box: Auto lets the server decide from
 * the message, On always searches, Off never does.
 */
export const INTELLIGENCE_WEB_SEARCH_MODES = ['auto', 'on', 'off'] as const;
export type IntelligenceWebSearchMode = (typeof INTELLIGENCE_WEB_SEARCH_MODES)[number];

/** Longest message a person can send. */
export const INTELLIGENCE_MAX_PROMPT_CHARS = 20_000;
/** Longest conversation title. */
export const INTELLIGENCE_MAX_TITLE_CHARS = 120;
/** Most files that can be attached to one message. */
export const INTELLIGENCE_MAX_FILES = 3;

const idSchema = z
  .string()
  .regex(/^[A-Za-z0-9_-]{1,64}$/, { error: 'We could not find that conversation.' });

export const conversationIdSchema = z.strictObject({ conversationId: idSchema });

/** Title without control characters, with spaces collapsed. */
export function cleanTitle(value: string): string {
  return value
    .replace(/[\u0000-\u001f\u007f]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

export const renameConversationSchema = z.strictObject({
  conversationId: idSchema,
  title: z
    .string()
    .transform(cleanTitle)
    .pipe(
      z
        .string()
        .min(1, { error: 'Enter a title.' })
        .max(INTELLIGENCE_MAX_TITLE_CHARS, {
          error: `Titles can be up to ${INTELLIGENCE_MAX_TITLE_CHARS} characters.`,
        }),
    ),
});

export const sendMessageSchema = z.strictObject({
  /** Omitted to start a new conversation. */
  conversationId: idSchema.optional(),
  content: z
    .string()
    .max(INTELLIGENCE_MAX_PROMPT_CHARS, {
      error: `Messages can be up to ${INTELLIGENCE_MAX_PROMPT_CHARS.toLocaleString('en-US')} characters.`,
    })
    .refine((value) => value.trim().length > 0, { error: 'Write a message first.' }),
  capability: z.enum(INTELLIGENCE_CAPABILITIES),
  webSearch: z.enum(INTELLIGENCE_WEB_SEARCH_MODES).default('auto'),
  fileIds: z
    .array(z.string().regex(/^[A-Za-z0-9-]{1,64}$/, { error: 'We could not find that file.' }))
    .max(INTELLIGENCE_MAX_FILES, { error: `Attach up to ${INTELLIGENCE_MAX_FILES} files.` })
    .default([]),
  /** Generated by the browser for each send, so a repeated submission does not run twice. */
  requestKey: z.uuid(),
});

export type SendMessageInput = z.infer<typeof sendMessageSchema>;

/** A title from the first message: its first line, shortened. */
export function titleFromPrompt(prompt: string): string {
  const firstLine = cleanTitle(prompt.split('\n').find((line) => line.trim()) ?? '');
  return firstLine.length <= 80 ? firstLine : `${firstLine.slice(0, 79).trimEnd()}…`;
}
